### PR TITLE
Add directory to create named pipes in for Mac

### PR DESCRIPTION
**Pull request by takluyver**
Closes gh-5

@Honestpuck, thanks for the tip. Care to take this for a test drive?

### CODE REVIEW

**Comment by Honestpuck** [comment]
Sure. The latest tar ball seems not to want to install on my Mac, but if you tell me how to get your patched one I'll grab it.

BTW - here's what I get when I try the install 👍 

```
/Users/tonyw/anaconda/envs/py3k/bin/python3
INFO:batislib.install:Installing system packages
WARNING:batislib.install:Couldn't find dependencies for this distro. Please ensure these are installed: Python 3
WARNING:batislib.install:Removing existing directory /Users/tonyw/.local/share/installed-applications/redsnail
INFO:batislib.install:Copying application directory to /Users/tonyw/.local/share/installed-applications/redsnail
INFO:batislib.install:Symlinking commands to /Users/tonyw/.local/bin
WARNING:batislib.install:Replacing file at /Users/tonyw/.local/bin/redsnail
INFO:batislib.install:Installing icons
WARNING:batislib.install:Replacing file at /Users/tonyw/.local/share/icons/hicolor/48x48/apps/redsnail.png
WARNING:batislib.install:xdg-icon-resource is not available
INFO:batislib.install:Installing desktop file: './batis_info/desktop/redsnail.desktop'
WARNING:batislib.install:Replacing file at /Users/tonyw/.local/share/applications/redsnail.desktop
WARNING:batislib.install:update-desktop-database is not available
Traceback (most recent call last):
  File "./batis_info/selfinstall.py", line 12, in <module>
    ApplicationInstaller(sys.argv[1], scheme).install()
  File "/Users/tonyw/Downloads/redsnail/batis_info/batislib/install.py", line 286, in install
    self.write_manifest()
  File "/Users/tonyw/Downloads/redsnail/batis_info/batislib/install.py", line 249, in write_manifest
    'batis_info', 'installed_files.json'), 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/tonyw/.local/share/installed-applications/./batis_info/installed_files.json'
(
```

**Comment by takluyver** [comment]
The tarball won't work, you'll have to get it from the repository:

```
git clone https://github.com/takluyver/redsnail
cd redsnail
git checkout mac-support
# This step will need pip and bower:
make deps
./redsnail
```

**Comment by Honestpuck** [comment]
OK. That installs fine but Apple don't install python3 so the `#!/usr/bin/python3` line in `./redsnail` won't work. Unfortunately the location people will then install Python 3 is not certain. `python3 redsnail`on the command line works though.

screen shot 2016-07-11 at 11 34 52 am

**Comment by takluyver** [comment]
Thanks, I've tweaked the README to tell people to run with `python3` explicitly. I'll open a new issue for Mac packaging

**Pull request merged**
